target("dep1", function () 
    set_kind("static")
    add_files("dep1.cpp")
    add_packages("boost", { public = true })
end)

target("dep2", function () 
    set_kind("binary")
    add_files("dep2.cpp")
    add_deps("dep1")
end)