type: play
name: test.play.com
publish_domain: test.publish.com
key_file: test.play.com.key
cert_file: test.play.com.crt
apps:
  - name: app
    # play_auth_check:
    #   params:
    #     key: string(sys@test.publish.com)
    #     time: get_time()
    #     token: md5_upper(${params[key]}/${stream}/${url_params[expire]})  #sys@test.publish.com/teststreamtitle/1792866744
    #   checks:
    #     - ${url_params[token]} == ${params[token]}
    #     - ${url_params[expire]} > ${params[time]}
    # push_to:
    #   - protocol: rtmp
    #     url: rtmp://zlm.com:1935/{app}/{stream}
    #     params:
    #       time: get_time()
    #       sign: md5_upper(sys@test.publish.com/{domain}/{app}/{stream}/{params[time]})
    #   - protocol: rtmp
    #     url: rtmp://test.publish.com:1935/{app}/{stream}_a
    #     params:
    #       time: get_time()
    #       sign: md5_upper(sys@test.publish.com/{domain}/{app}/{stream}/{params[time]})
    # source:
    #   protocol: rtmp
    #   url: rtmp://zlm.com:1935/{app}/{stream}
    #   params:
    #     time: get_time()
    #     sign: md5_upper(sys@test.publish.com/{domain}/{app}/{stream}/{params[time]})
    # http_callbacks: &流回调
    #   on_publish: 
    #     - url: "http://mms.com:8082/api/on_publish"
    #       key: "123456"

    # publish_auth_check:
    #   params:
    #     key: string(sys@test.publish.com)
    #     time: get_time()
    #     token: md5_upper({params[key]}/{stream}/{url_params[expire]})  #sys@test.publish.com/teststreamtitle/1792866744
    #   checks:
    #     - "{url_params[token]} == {params[token]}"                     # url的token必须和计算的一致
    #     - "{url_params[expire]} > {params[time]}"                      # url的expire必须大于当前系统时间

    # auth_checks:
    #   - 推流鉴权1: &推流鉴权1
    #       params:
    #         SignStr: string(/{app}/{stream}?e={url_params[e]})            #'/app/test?expire=1584522520'
    #         AccessKey: string(7O7hf7Ld1RrC_fpZdFvU8aCgOPuhw2K4eapYOdII)
    #         SecretKey: string(312ae9gd2BrCfpTdF4U8aIg9Puh62K4eEGY72Ea_)   #
    #         HMAC: hmac_sha1({params[SecretKey]},{params[SignStr]})        # hmac_sha1(312ae9gd2BrCfpTdF4U8aIg9Puh62K4eEGY72Ea_,/app/test?expire=1792849416)
    #         Base64: base64({params[HMAC]})                                # I8KP0Qm7lGgP683HHriKLCFKXR4=
    #         Token: string({params[AccessKey]}:{params[Base64]})           # 7O7hf7Ld1RrC_fpZdFvU8aCgOPuhw2K4eapYOdII:I8KP0Qm7lGgP683HHriKLCFKXR4=
    #         time: get_time()
    #       checks:
    #         - "{url_params[token]} == {params[Token]}"
    #         - "{url_params[e]} < {params[time]}"
    #   - 推流鉴权2: &推流鉴权2 
    #       checks:
    #         - "{url_params[publishKey]} == 123" # 静态鉴权(static)
    #   - 播放鉴权: &播放鉴权
    #       params:
    #         key: string(sys@test.publish.com)
    #         time: get_time()
    #         token: md5_upper({params[key]}/{stream}/{url_params[expire]})  #sys@test.publish.com/teststreamtitle/1792866744
    #       checks:
    #         - "{url_params[token]} == {params[token]}"
    #         - "{url_params[expire]} > {params[time]}"
    # rtmp:
    #   http_callbacks: *流回调
    #   play_auth_check: *播放鉴权
    # rtsp:
    #   publish_auth_check: *推流鉴权2
    #   play_auth_check: *播放鉴权
    # webrtc:
    #   publish_auth_check: *推流鉴权1
    #   play_auth_check: *播放鉴权

