includes("src/aac")
includes("src/av1")
includes("src/g711")
includes("src/h264")
includes("src/hevc")
includes("src/mp3")
includes("src/opus")

-- TODO: track??
target("codec", function ()
    set_kind("static")
    add_files("src/track.cpp")
    add_includedirs("include", {public = true})
    add_deps("codec_aac", "codec_av1", "codec_g711", "codec_h264", "codec_hevc", "codec_mp3", "codec_opus")
end)
